"""提示词模块 - 统一导出所有提示词常量"""
from .base import ANTI_HALLUCINATION_PROTOCOL, HUMAN_STYLE_TIPS
from .roles import ROLE_SOUL_SETTINGS, PERSONALITY_TEMPLATES
from .strategies import SPEECH_TIPS, VOTE_TIPS, PK_TIPS, LAST_WORDS_TIPS
from .templates import ROLE_PROMPTS
from .events import PEACEFUL_NIGHT_TIPS, DOUBLE_DEATH_TIPS, PERSONALITY_NAMES
from .rules import GAME_RULES
from .tactics import (
    SITUATION_TEMPLATE,
    TACTICAL_DIRECTIVES,
    DUEL_CONTEXT_TEMPLATE,
    BEHAVIOR_ANALYSIS_TIPS,
    BEHAVIOR_TAG_DEFINITIONS
)

__all__ = [
    # 基础协议
    'ANTI_HALLUCINATION_PROTOCOL',
    'HUMAN_STYLE_TIPS',
    # 游戏规则
    'GAME_RULES',
    # 角色设定
    'ROLE_SOUL_SETTINGS',
    'PERSONALITY_TEMPLATES',
    'PERSONALITY_NAMES',
    # 策略提示词
    'SPEECH_TIPS',
    'VOTE_TIPS',
    'PK_TIPS',
    'LAST_WORDS_TIPS',
    # 场景模板
    'ROLE_PROMPTS',
    # 特殊事件
    'PEACEFUL_NIGHT_TIPS',
    'DOUBLE_DEATH_TIPS',
    # 战术分析
    'SITUATION_TEMPLATE',
    'TACTICAL_DIRECTIVES',
    'DUEL_CONTEXT_TEMPLATE',
    'BEHAVIOR_ANALYSIS_TIPS',
    'BEHAVIOR_TAG_DEFINITIONS',
]
